import "./globals.css";
import Provider from "./Provider";
import { TabItem } from "@/components/Tabs";
import Profile from "@/components/Profile";
import Tabs from "@/components/Tabs";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const tabItems: TabItem[] = [
	{
		key: 1,
		label: "プロフィール",
		href: "/",
	},
	{
		key: 2,
		label: "感謝の声",
		href: "/rating",
	},
	{
		key: 3,
		label: "タイムライン",
		href: "/timeline",
	},
];
export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Provider>
					<div className="text-center my-2">カウンセラー</div>

					<Profile />
					<div className="m-4">
						<Tabs className="mb-4" items={tabItems} />
					</div>
					{children}
				</Provider>
			</body>
		</html>
	);
}
